/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eu.bato.anyoffice.trayapp;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author bryndza
 */
public class SwitchToDndFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form SwitchToDndFrame
     */
    public SwitchToDndFrame() {
        initComponents();
        showOnTop(false);
        this.setLocationRelativeTo(null);
    }
    
    void display(){
        showOnTop(true);
        jButtonYes.setSelected(true);
    }
    
    private void showOnTop(boolean show){
        this.setAlwaysOnTop(show);
        this.setVisible(show);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonYes = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMinutes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();

        setTitle("Switch to Do Not Disturb?");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("Would you like to switch to Do Not Disturb state now?");

        jButtonYes.setText("Yes");
        jButtonYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonYesMouseClicked(evt);
            }
        });
        jButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYesActionPerformed(evt);
            }
        });

        jButtonNo.setText("No");
        jButtonNo.setMaximumSize(new java.awt.Dimension(49, 23));
        jButtonNo.setMinimumSize(new java.awt.Dimension(49, 23));
        jButtonNo.setPreferredSize(new java.awt.Dimension(49, 23));
        jButtonNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNoMouseClicked(evt);
            }
        });
        jButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoActionPerformed(evt);
            }
        });

        jLabel2.setText("Remind me in");

        jTextFieldMinutes.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldMinutes.setText("15");
        jTextFieldMinutes.setMaximumSize(new java.awt.Dimension(18, 20));
        jTextFieldMinutes.setMinimumSize(new java.awt.Dimension(18, 20));
        jTextFieldMinutes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMinutesKeyReleased(evt);
            }
        });

        jLabel3.setText("minutes:");

        jButtonOk.setText("OK");
        jButtonOk.setMaximumSize(new java.awt.Dimension(49, 23));
        jButtonOk.setMinimumSize(new java.awt.Dimension(49, 23));
        jButtonOk.setPreferredSize(new java.awt.Dimension(49, 23));
        jButtonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOkMouseClicked(evt);
            }
        });
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonYes)
                    .addComponent(jButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonYesMouseClicked
        
    }//GEN-LAST:event_jButtonYesMouseClicked

    private void jButtonNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNoMouseClicked
        
    }//GEN-LAST:event_jButtonNoMouseClicked

    private void jButtonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOkMouseClicked
        
    }//GEN-LAST:event_jButtonOkMouseClicked

    private void jButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYesActionPerformed
        TrayIconManager.getInstance().updateState(PersonStateManager.getInstance().setState(PersonState.DO_NOT_DISTURB));
        showOnTop(false);
    }//GEN-LAST:event_jButtonYesActionPerformed

    private void jButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoActionPerformed
        showOnTop(false);
    }//GEN-LAST:event_jButtonNoActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        remindIn(jTextFieldMinutes);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jTextFieldMinutesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMinutesKeyReleased
        if (evt.getKeyCode() == (KeyEvent.VK_ENTER)){
            jButtonOkActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldMinutesKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if (evt.getKeyCode() == (KeyEvent.VK_ENTER)){
            jButtonYesActionPerformed(null);
        }
    }//GEN-LAST:event_formKeyReleased

    private void remindIn(JTextField jTextFieldMinutes){
        int minutes;
        try{
            minutes = Integer.parseInt(jTextFieldMinutes.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Please use only numeric characters.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (minutes < 1) {
            JOptionPane.showMessageDialog(rootPane, "Please use positive number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "Not supported yet.");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldMinutes;
    // End of variables declaration//GEN-END:variables
}
