INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (1, 'AVAILABLE', 900000, 0);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION, DEFAULTSUCCESSOR_ID) values (2, 'DND', 0, 2700000, 1);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION, DEFAULTSUCCESSOR_ID) values (3, 'AWAY', 0, 0, 1);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION, DEFAULTSUCCESSOR_ID) values (4, 'IN A MEETING', 0, 0, 1);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION, DEFAULTSUCCESSOR_ID) values (5, 'SHORT STATE BEFORE DND', 0, 15000, 2);