INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (1, 'AVAILABLE', 15, 100);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (2, 'DND', 15, 100);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (3, 'AWAY', 15, 100);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (4, 'IN A MEETING', 15, 100);