INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (1, 'AVAILABLE', 15, 100);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (2, 'DND', 15, 100);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (3, 'AWAY', 15, 100);
INSERT INTO STATE (ID, NAME, MINDURATION, MAXDURATION) values (4, 'IN A MEETING', 15, 100);
INSERT INTO ENTITY (DISPLAYNAME, DESCRIPTION, STATE_ID) values ('Administrator', 'The administrator', 1);
INSERT INTO PERSON (ENTITY_ID, USERNAME, ROLE, PASSWORD) values (1, 'admin', 'ADMIN', 'ceb4f32325eda6142bd65215f4c0f371');